/**
 * cet6-material.js — 六级复习资料（4.1.0）
 *
 * 与 cet6-tips.js 的分工：那边 4 章是「方法」（怎么听、怎么读、怎么写），
 * 这里是「资料」（词、词组、句型、同义替换、考场流程），标签不同：
 *   技巧 = 方法
 *   复习资料 = 查得到的料
 *
 * 每篇都是按 ## 分小节的长文 —— 在记录阅读页里有目录尺，能直接跳小节。
 * 内容对准实测短板：听力 140（场景词 + 视听一致）、阅读 131（同义替换 + 时间分配）、
 * 写作翻译 96（模板句 + 简单句优先）。
 */

/* ---------- 1. 高频词速记（按话题分组） ---------- */
export const VOCAB = [
  '## 一、教育学习',
  '- acquire 获得（acquire knowledge）',
  '- curriculum 课程体系 · compulsory 必修的 · elective 选修的',
  '- tuition 学费 · scholarship 奖学金 · loan 贷款',
  '- academic 学术的 · seminar 研讨课 · lecture 讲座',
  '- assess 评估 · evaluate 评价 · criterion 标准',
  '- graduate 毕业 · undergraduate 本科生 · postgraduate 研究生',
  '- discipline 学科；纪律 · faculty 全体教员',
  '- literacy 读写能力 · numeracy 计算能力',
  '',
  '## 二、工作职场',
  '- recruit 招聘 · applicant 应聘者 · candidate 候选人',
  '- resume 简历 · interview 面试 · probation 试用期',
  '- salary 薪水 · bonus 奖金 · allowance 津贴',
  '- promotion 晋升 · resign 辞职 · retire 退休',
  '- workload 工作量 · deadline 截止期 · shift 轮班',
  '- colleague 同事 · supervisor 主管 · subordinate 下属',
  '- expertise 专业知识 · qualification 资历',
  '- efficiency 效率 · productivity 生产率',
  '',
  '## 三、经济商业',
  '- economy 经济 · economic 经济的 · economical 省钱的（三个别混）',
  '- revenue 收入 · expense 支出 · profit 利润 · budget 预算',
  '- investment 投资 · capital 资本 · asset 资产 · debt 债务',
  '- inflation 通胀 · recession 衰退 · recovery 复苏',
  '- consumer 消费者 · retail 零售 · wholesale 批发',
  '- negotiate 谈判 · contract 合同 · bid 投标',
  '- subsidy 补贴 · tariff 关税 · quota 配额',
  '- boost 提振 · decline 下滑 · fluctuate 波动',
  '',
  '## 四、科技环保',
  '- innovation 创新 · breakthrough 突破 · patent 专利',
  '- artificial intelligence 人工智能 · algorithm 算法 · automation 自动化',
  '- digital 数字的 · virtual 虚拟的 · wireless 无线的',
  '- emission 排放 · carbon 碳 · renewable 可再生的',
  '- pollution 污染 · recycle 回收 · sustainable 可持续的',
  '- ecosystem 生态系统 · biodiversity 生物多样性',
  '- energy consumption 能源消耗 · efficiency 能效',
  '- conservation 保护 · awareness 意识',
  '',
  '## 五、社会文化',
  '- tradition 传统 · custom 习俗 · heritage 遗产',
  '- urban 城市的 · rural 农村的 · suburb 郊区',
  '- population 人口 · ageing population 老龄化',
  '- welfare 福利 · charity 慈善 · volunteer 志愿者',
  '- inequality 不平等 · discrimination 歧视 · diversity 多样性',
  '- generation gap 代沟 · peer pressure 同辈压力',
  '- community 社区 · public service 公共服务',
  '- civilized 文明的 · courtesy 礼貌',
  '',
  '## 六、怎么用这份词表（每天 20 分钟）',
  '1. 只记「词 + 一个搭配」，不背孤立单词（acquire knowledge 比 acquire 好记）。',
  '2. 当天记的词，晚上听真题音频时留意：听到就画个勾，第二天先复习画勾的。',
  '3. 写作/翻译时主动换词：想说 think 就换 hold the view that，想说 important 就换 significant。',
  '4. 一次记 20 个，隔天复习 + 再记 20 个；记不住的单独抄一行，周末只看那一行。'
].join('\n')

/* ---------- 2. 写作模板库 ---------- */
export const WRITING_LIB = [
  '## 一、三段式骨架（背这一张就够）',
  '- 首段（2 句）：第 1 句改写题目（把题目换个说法说一遍）；第 2 句给立场（I believe / In my view）。',
  '- 中段（4 句）：两个理由，每个理由后面跟一句具体例子（Take … for example）。',
  '- 尾段（1 句）：重申立场（Therefore / In short + 换个说法重说观点）。',
  '全程 150-180 词。句数写死，考场上只填内容。',
  '',
  '## 二、万能句 10 条（换词不换结构）',
  '1. There is no denying that … （不可否认……）',
  '2. It is widely accepted that … （人们普遍认为……）',
  '3. Take … for example / For instance, … （以……为例）',
  '4. Although … , … （虽然……但是……）',
  '5. Not only … but also … （不仅……而且……；写不对就拆成两句）',
  '6. The reason why … is that … （……的原因在于）',
  '7. Compared with … , … （与……相比）',
  '8. It is high time that we took action to … （该行动了）',
  '9. What matters most is that … （最重要的是）',
  '10. Only in this way can we … （只有这样我们才能；注意倒装）',
  '',
  '## 三、过渡词 15 个（别只用一个）',
  '- 顺承：besides / moreover / in addition / what is more',
  '- 转折：however / nevertheless / on the contrary / instead',
  '- 因果：therefore / thus / as a result / consequently',
  '- 举例：for example / for instance / take … as an example',
  '- 总结：in short / to sum up / in conclusion',
  '',
  '## 四、常用替换（把小学词换成得分词）',
  '- important → significant / crucial',
  '- think → believe / hold the view that',
  '- many → numerous / a considerable number of',
  '- good at → be proficient in',
  '- get → obtain / acquire',
  '- help → contribute to / be conducive to',
  '',
  '## 五、考场 30 分钟怎么用',
  '1. 0-3 分钟：读题 + 在草稿纸写三段提纲（每段写关键词，不写整句）。',
  '2. 3-23 分钟：写正文。首段与尾段优先写，中段例子想不出就写「身边的事」。',
  '3. 23-28 分钟：只查三件事 —— 主谓一致、时态统一、拼写与单复数。',
  '4. 28-30 分钟：通读一遍，把明显写错的句子改简单（宁可短句，不要错句）。'
].join('\n')

/* ---------- 3. 翻译高频词组 ---------- */
export const TRANSLATION_LIB = [
  '## 一、中国文化',
  '- 有着悠久历史 has a long history',
  '- 传统文化 traditional culture',
  '- 象征 symbolize / be a symbol of',
  '- 春节 the Spring Festival · 中秋节 the Mid-Autumn Festival',
  '- 剪纸 paper cutting · 书法 calligraphy · 京剧 Peking Opera',
  '- 团圆 family reunion · 拜年 pay New Year calls',
  '- 传统美德 traditional virtue · 代代相传 pass down from generation to generation',
  '- 越来越受欢迎 become increasingly popular',
  '',
  '## 二、教育',
  '- 素质教育 quality-oriented education',
  '- 义务教育 compulsory education',
  '- 录取 be admitted to · 毕业 graduate from',
  '- 培养兴趣 cultivate an interest in',
  '- 终身学习 lifelong learning',
  '- 提高教学质量 improve the quality of teaching',
  '- 学生数量 the number of students（谓语用单数）',
  '- 重视 attach importance to',
  '',
  '## 三、经济与科技',
  '- 高速发展 develop rapidly / rapid development',
  '- 国民经济 national economy',
  '- 生活水平 living standard · 稳步提升 improve steadily',
  '- 互联网技术 Internet technology · 5G 网络 the 5G network',
  '- 移动支付 mobile payment · 电子商务 e-commerce',
  '- 创新 drive innovation · 应用广泛 be widely used',
  '- 为……提供便利 provide convenience for …',
  '- 发挥重要作用 play an important role in',
  '',
  '## 四、社会与环保',
  '- 环境保护 environmental protection',
  '- 减少污染 reduce pollution',
  '- 节约资源 save resources',
  '- 可持续发展 sustainable development',
  '- 公众意识 public awareness',
  '- 政府采取措施 the government takes measures to …',
  '- 人口老龄化 population ageing',
  '- 改善生活质量 improve the quality of life',
  '',
  '## 五、万能句型 6 条（不会写长句就用它们）',
  '1. China is a country with … （中国是一个有着……的国家）',
  '2. With the development of … , … （随着……的发展）',
  '3. It is important for us to … （对我们来说……很重要）',
  '4. More and more people … （越来越多的人……）',
  '5. China has made great progress in … （中国在……方面取得了巨大进步）',
  '6. This not only … but also … （就写 not only 那句；写不对就拆两句）',
  '',
  '## 六、写完只查三件事',
  '1. 主谓一致（第三人称单数别漏 s）。',
  '2. 时态统一 —— 拿不准就全用一般现在时。',
  '3. 单复数与拼写。这三条能捞回 10 分以上。'
].join('\n')

/* ---------- 4. 听力场景词 ---------- */
export const LISTENING_LIB = [
  '## 一、校园',
  '- lecture 讲座 · seminar 研讨课 · tutorial 辅导课',
  '- assignment 作业 · essay 论文 · deadline 截止期',
  '- library 图书馆 · renew 续借 · overdue 逾期',
  '- professor 教授 · tutor 导师 · classmate 同学',
  '- exam 考试 · grade 成绩 · credit 学分',
  '- dormitory 宿舍 · canteen 食堂 · campus 校园',
  '- scholarship 奖学金 · tuition 学费 · semester 学期',
  '- register 注册 · course 课程 · schedule 课表',
  '',
  '## 二、职场',
  '- interview 面试 · applicant 应聘者 · position 职位',
  '- salary 薪水 · benefit 福利 · promotion 晋升',
  '- meeting 会议 · agenda 议程 · deadline 截止期',
  '- colleague 同事 · manager 经理 · client 客户',
  '- overtime 加班 · shift 轮班 · vacation 假期',
  '- resign 辞职 · recruit 招聘 · contract 合同',
  '- report 报告 · project 项目 · budget 预算',
  '- colleague 同事 · department 部门 · branch 分公司',
  '',
  '## 三、交通出行',
  '- flight 航班 · delay 延误 · cancel 取消',
  '- boarding pass 登机牌 · luggage 行李 · check in 办理登记',
  '- platform 站台 · departure 出发 · arrival 到达',
  '- traffic jam 堵车 · rush hour 高峰时段',
  '- fare 车费 · ticket 车票 · refund 退款',
  '- book a room 订房 · reservation 预订 · vacancy 空房',
  '- deposit 押金 · check out 退房 · service 服务',
  '- direction 方向 · map 地图 · shortcut 近路',
  '',
  '## 四、健康医疗',
  '- symptom 症状 · prescription 处方 · pharmacy 药房',
  '- appointment 预约 · clinic 诊所 · ward 病房',
  '- diet 饮食 · nutrition 营养 · obesity 肥胖',
  '- exercise 锻炼 · stress 压力 · insomnia 失眠',
  '- treatment 治疗 · recover 康复 · allergy 过敏',
  '- insurance 保险 · fee 费用 · emergency 急诊',
  '- checkup 体检 · blood pressure 血压',
  '- habit 习惯 · balanced 均衡的',
  '',
  '## 五、天气与购物',
  '- forecast 预报 · shower 阵雨 · humid 潮湿的',
  '- temperature 气温 · breeze 微风 · thunderstorm 雷雨',
  '- discount 折扣 · refund 退款 · receipt 收据',
  '- try on 试穿 · size 尺码 · exchange 换货',
  '- brand 品牌 · price tag 价签 · cashier 收银台',
  '- out of stock 缺货 · on sale 打折 · warranty 保修',
  '',
  '## 六、讲座与新闻常见框架词',
  '- today we will focus on … （今天讲……）',
  '- first of all / secondly / finally （分层提示，考点常在「其次」后）',
  '- on the contrary 相反 · in contrast 相比之下',
  '- for example / to illustrate 举例（例子本身不考，结论才考）',
  '- therefore 因此 · as a result 结果是（结论句是考点）',
  '- to sum up 总结（结尾常考）',
  '',
  '## 七、怎么用这份表',
  '1. 每天挑一个场景，把词读三遍（会读才可能听懂）。',
  '2. 做真题听力时，听到场景词就在旁边画勾 —— 画勾密度就是你的听力安全感来源。',
  '3. 错题对照：如果整段没听懂，先查是不是场景词不认识。'
].join('\n')

/* ---------- 5. 阅读同义替换表 ---------- */
export const READING_LIB = [
  '## 一、为什么同义替换决定分数',
  '正确选项几乎不会照抄原文，而是把原文换个说法。找不到「原词」就慌，是阅读丢分的主要原因。',
  '做错题时，请把「题干词 → 原文词」这条替换写在旁边，比抄答案有用十倍。',
  '',
  '## 二、常见替换（动词）',
  '- increase → rise / grow / go up / soar',
  '- decrease → decline / drop / fall / reduce',
  '- cause → lead to / result in / give rise to',
  '- solve → tackle / address / deal with',
  '- improve → enhance / boost / upgrade',
  '- support → back / favor / be in favor of',
  '- oppose → object to / be against',
  '- ignore → overlook / neglect / turn a blind eye to',
  '- allow → permit / enable / make it possible',
  '- need → require / call for / demand',
  '',
  '## 三、常见替换（名词与形容词）',
  '- important → significant / crucial / vital / essential',
  '- difficult → tough / challenging / demanding',
  '- many → numerous / a large number of / a host of',
  '- few → scarce / rare / limited',
  '- advantage → benefit / strength / merit',
  '- disadvantage → drawback / downside / weakness',
  '- reason → cause / factor / explanation',
  '- result → outcome / consequence / finding',
  '- problem → issue / challenge / obstacle',
  '- idea → notion / concept / view',
  '',
  '## 四、题干与原文的连接词',
  '- because → due to / owing to / as a result of',
  '- although → despite / in spite of / while',
  '- if → provided that / as long as / on condition that',
  '- so that → in order to / so as to',
  '- about → regarding / concerning / with respect to',
  '- according to → based on / in light of',
  '',
  '## 五、选项里的三个陷阱',
  '1. 出现原文原词：多半是干扰项（正确项常做改写）。',
  '2. 出现绝对词：must / never / all / only / completely —— 先怀疑。',
  '3. 出现「常识正确」但与原文无关的内容：答案必须能在原文找到依据。',
  '',
  '## 六、段落匹配的两步走',
  '1. 题干里圈一个「不会变形」的词：数字、大写专有名词、斜体词。',
  '2. 逐段只读首句与末句（段落主旨常在这两句），配上一个划掉一个；剩下的用排除法。'
].join('\n')

/* ---------- 6. 考场流程与时间分配 ---------- */
export const EXAM_FLOW = [
  '## 一、整卷顺序与时间（四级六级通用）',
  '1. 写作 30 分钟（不能提前做听力，写作结束才发听力卷）。',
  '2. 听力 25 分钟（放音结束立刻收答题卡，没有回头补涂的时间）。',
  '3. 阅读 40 分钟：选词填空 5 分钟 → 段落匹配 10 分钟 → 仔细阅读 25 分钟。',
  '4. 翻译 30 分钟。',
  '自己模考必须严格计时，顺序不要改 —— 换个顺序做，正确率与心态都会变。',
  '',
  '## 二、听力最重要的两条纪律',
  '1. 答题卡边听边涂（听力结束就收卡，来不及补）。',
  '2. 一句没听懂就放下，跟着音频走；停下来回想，后面三句全丢。',
  '',
  '## 三、阅读的取舍（投入产出比排序）',
  '- 仔细阅读每题 14 分 → 优先，25 分钟给两篇。',
  '- 段落匹配每题约 7 分 → 其次，10 分钟。',
  '- 选词填空每题约 3.5 分、全国正确率不到 30% → 限时 5 分钟；做不完全选同一项（别留空）。',
  '',
  '## 四、翻译与写作的共同纪律',
  '1. 空着一句就是零分 —— 不会的句子用简单句写出来，写完就有分。',
  '2. 宁写短句不写错句：一句一主一谓。',
  '3. 收尾留 2-4 分钟只查三件事：主谓一致、时态统一、拼写与单复数。',
  '',
  '## 五、考前一周做什么',
  '1. 每两天一套完整真题（严格计时，含涂卡）。',
  '2. 只复盘错题的三样东西：定位词、同义替换、错因归类（词不认识 / 定位错 / 想多了）。',
  '3. 背熟写作三段骨架与 10 条万能句；翻译只背高频词组，不再学新语法。',
  '',
  '## 六、考前一夜与当天',
  '- 考前一夜：不刷新题，只过一遍作文模板与高频词表，正常时间睡觉。',
  '- 当天：带齐准考证、身份证、2B 铅笔、黑色签字笔（备一支）、橡皮；听力耳机提前试音。',
  '- 心态：六级不是选拔考试，题型固定、套路固定，按流程做完就是正常发挥。'
].join('\n')

/** 复习资料篇目（标签为「复习资料」，与 4 章「技巧」分开筛） */
export const CET6_MATERIALS = [
  { client_id: 'mat_cet6_vocab', title: '六级·高频词速记（6 大话题，按搭配记）', chapter: '词汇', content: VOCAB },
  { client_id: 'mat_cet6_writing', title: '六级·写作模板库（骨架 / 万能句 / 过渡词 / 替换）', chapter: '写作', content: WRITING_LIB },
  { client_id: 'mat_cet6_translation', title: '六级·翻译高频词组（文化 / 教育 / 经济 / 社会）', chapter: '翻译', content: TRANSLATION_LIB },
  { client_id: 'mat_cet6_listening', title: '六级·听力场景词（校园 / 职场 / 交通 / 医疗 / 购物）', chapter: '听力', content: LISTENING_LIB },
  { client_id: 'mat_cet6_reading', title: '六级·阅读同义替换表（找不着原词就看它）', chapter: '阅读', content: READING_LIB },
  { client_id: 'mat_cet6_flow', title: '六级·考场时间分配与流程（照着做就行）', chapter: '考场', content: EXAM_FLOW }
]